import pandas as pd
marks=pd.Series([85,78,90,88],index=["maths","science","english","computer"])
print(marks)
print("highest marks:",max(marks))
print("lowest marks:",min(marks))
print("Total marks:",marks.sum())
print("Average marks:",marks.mean())

marks_df=pd.DataFrame({"name":["anu","binu","chithra","ramesh"],"marks":[85,78,90,88]},index=["maths","science","english","computer"])
print(marks_df)
total_marks=marks_df["marks"].sum()
print("Total marks:", total_marks)
average_marks=marks_df["marks"].mean()
print("Average marks:", average_marks)
print(type(marks))
print(type(marks_df))
